apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpenv
  labels:
    app: httpenv
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"httpenv"},"name":"httpenv","namespace":"default"},"spec":{"minReadySeconds":0,"replicas":1,"selector":{"matchLabels":{"app":"httpenv"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"httpenv"}},"spec":{"containers":[{"image":"httpd","name":"httpd","ports":[{"containerPort":80}]}]}}}
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app: httpenv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpenv
    spec:
      containers:
        - image: httpd
          name: httpd
          ports:
            - containerPort: 80
